### ISSUE TITLE
Number method signature is incorrect 

### ISSUE THREAD

**Issue by extsoft** [krizzis/PBC-Vbeliaev#3]
https://github.com/krizzis/PBC-Vbeliaev/blob/e67ade00167d8559a49fd336a353dddfa77594b0/my_app/Numbers_pairs.py#L5

Visit https://gist.github.com/extsoft/bf1b9884cbaccf1eb2efd0330ae542c7#3-numbers-pairs to get the details.

**Comment by krizzis** [comment]
https://github.com/krizzis/PBC-Vbeliaev/commit/fa137de34cbcb1de7d6c5f823a4b7970d96fa1db
