### ISSUE TITLE
Missed return

### ISSUE THREAD

**Issue by extsoft** [krizzis/PBC-Vbeliaev#6]
https://github.com/krizzis/PBC-Vbeliaev/blob/4690a77eb6cbca1ec21e91d98c7323d3bafc746b/pbc/sel_grid/sel_grid.py#L44

**Comment by krizzis** [comment]
https://github.com/krizzis/PBC-Vbeliaev/commit/b4dd864d57b3480d0a3c923dd544d79a7193a393
